Resources:
  AppNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f9cf087c1f27d9b1
      KeyName: dev-cc
      SecurityGroups:
        - !Ref AppNodeSG
      IamInstanceProfile: !Ref EC2CCProfile
      UserData: !Base64 |
        #cloud-boothook
        #!/bin/bash
        sudo rm -rf /home/ubuntu/prime_cc
        mkdir /home/ubuntu/prime_cc
        key=`aws s3 ls s3://onelink-cc-deployment/test-cc/MyApp/ --recursive | sort | tail -n 1 | awk '{print $4}'`
        aws s3 cp s3://onelink-cc-deployment/$key /home/ubuntu/prime_cc/
        zipname="$(cut -d'/' -f3 <<<"$key")"
        echo $zipname >> output.txt
        cd prime_cc
        chmod 0777 /home/ubuntu/prime_cc/$zipname
        echo "before unzip" > /home/ubuntu/output.txt
        sudo unzip -o /home/ubuntu/prime_cc/$zipname >> /home/ubuntu/output.txt
        echo $? >> /home/ubuntu/output.txt
        echo "end" >> /home/ubuntu/output.txt
        exit 0
  AppNodeSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: for the app nodes that allow ssh, http and docker ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
  EC2CCProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref EC2PrimeCCRole
  EC2PrimeCCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: prime-cc-ec2-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: prime-cc-ec2-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - "*"
                Resource:
                  - "*"
                Effect: Allow

